add noti jobs

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -58,8 +58,8 @@ jobs:
           path: dist
       - name: Deploy
         run: echo "Deploying..."
-      - name: Force failed
-        run: exit 1
+      # - name: Force failed
+      #   run: exit 1
 
   notify:
     runs-on: ubuntu-latest
