update files deploy and action

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -1,14 +1,25 @@
-name: Deploy React CSR
+name: Deploy React App
 on:
   push:
+    branches:
+      - main
+      - feature/**
+      - "!feature/authen"
   workflow_dispatch:
+  pull_request:
+    types:
+      - opened
+
+env:
+  BUN_VERSION: latest
+
 jobs:
   build:
     runs-on: ubuntu-latest
     steps:
       - name: Clone repo
         uses: actions/checkout@v5
-      - name: Install and Cache
+      - name: Install and cache
         uses: ./.github/actions/install-cache
       - name: Build
         run: bun run build
@@ -19,11 +30,11 @@ jobs:
         with:
           name: dist-folder
           path: dist/
-          
+
   deploy:
-    if: ${{ github.ref == 'refs/heads/main' }}
+    if: success()
     runs-on: ubuntu-latest
-    needs:
+    needs: 
       - build
     steps:
       - name: Download dist
@@ -33,3 +44,33 @@ jobs:
           path: dist
       - name: Deploy
         run: echo "Deploying..."
+      # - name: Force failed
+      #   run: exit 1
+
+  notify-failed:
+    runs-on: ubuntu-latest
+    needs:
+      - build
+      - deploy
+    if: failure() # failure() | cancelled() | always() | success()
+    steps:
+      - name: Discord notification
+        env:
+          DISCORD_WEBHOOK: https://discord.com/api/webhooks/1421697869458706533/W2UqZa7gD95EU7ixa4gQN3QLz3pWc3oFepvpv16XWxfpuMMTTiqbNULZWrBBmPfPlYBY
+        uses: Ilshidur/action-discord@master
+        with:
+          args: "# 🚨 Build Commit ${{ github.sha }} | Crafted by Nat49"
+
+  notify-success:
+    runs-on: ubuntu-latest
+    needs:
+      - build
+      - deploy
+    if: success() # failure() | cancelled() | always() | success()
+    steps:
+      - name: Discord notification
+        env:
+          DISCORD_WEBHOOK: https://discord.com/api/webhooks/1421697869458706533/W2UqZa7gD95EU7ixa4gQN3QLz3pWc3oFepvpv16XWxfpuMMTTiqbNULZWrBBmPfPlYBY
+        uses: Ilshidur/action-discord@master
+        with:
+          args: "# 🚀 Build Commit ${{ github.sha }} | Crafted by Nat49"
